version: '3.1'

services:

  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345